# Generated by Django 3.0.2 on 2020-02-14 12:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_cost', models.FloatField(blank=True, null=True)),
                ('measurements', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=255)),
                ('status', models.CharField(default='new', max_length=255)),
                ('advance_payment_amount', models.FloatField(default=0)),
                ('otp', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_valid_till', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('order_serial', models.IntegerField(default=1)),
                ('order_total', models.FloatField(default=0)),
                ('amount_paid', models.FloatField(default=0)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('base_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=orders.models.get_specification_type_upload_path)),
                ('is_custom', models.BooleanField(default=False)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_types', to='orders.Specification')),
            ],
        ),
        migrations.CreateModel(
            name='ParticularSpecificationTypePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Particular')),
                ('specification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.SpecificationType')),
            ],
        ),
        migrations.AddField(
            model_name='particular',
            name='specifications',
            field=models.ManyToManyField(related_name='particulars', to='orders.Specification'),
        ),
        migrations.CreateModel(
            name='OrderSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_specification_image', models.ImageField(blank=True, null=True, upload_to='custom_specification_images/')),
                ('customer_specification_image', models.ImageField(blank=True, null=True, upload_to='customer_specification_images/')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Specification')),
                ('specification_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.SpecificationType')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_link', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('razorpay_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_image', models.ImageField(upload_to='sample_materials')),
                ('description', models.TextField(blank=True, null=True)),
                ('measurements', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('images', models.ManyToManyField(to='orders.Image')),
                ('particular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Particular')),
                ('specifications', models.ManyToManyField(related_name='materials', to='orders.OrderSpecification')),
            ],
        ),
    ]
